### ISSUE TITLE
Great Job!

### ISSUE THREAD

**Issue by amrrs** [trafficonese/coinmarketcap_v2#1]
Hey @trafficonese I'm very sorry I missed your notification. Great job this one!

Will it work for existing users as it's or they'd be forced to take a Free API key?

**Comment by trafficonese** [comment]
Hey,

It should still work without an API key for all existing functions.

The functions I added need a key though.

**Comment by trafficonese** [comment]
I was just looking again at the code and found that I changed `get_marketcap_ticker_all` to `get_global_marketcap` without deprecating it. I will push a commit to fix that, so that all original functions are still supported.

**Comment by trafficonese** [comment]
I opened a PR https://github.com/amrrs/coinmarketcapr/pull/16

**Comment by amrrs** [comment]
btw, let me tell, I recently got notification from CRAN that I've not handled exceptions well in the package. That's how your i came back to your notification.

**Comment by trafficonese** [comment]
Do you mean the warnings / errors here? https://cran.rapporter.net/web/checks/check_results_coinmarketcapr.html

**Comment by amrrs** [comment]
After that error they sent me a notiifcation to get things cleaned up before the month end.

**Comment by trafficonese** [comment]
Could you tell me which exceptions, or what CRAN was unhappy about exactly?
If you could tell me, I will try to get some free time to fix them.

**Comment by amrrs** [comment]
@trafficonese it was about the responses from the API and when it fails. I'll have to check your code but when i glanced last time, you had handled it well with your own error messages. I'll give a look at it and update you, Thank you

**Comment by trafficonese** [comment]
I found some errors today, related to a Time-out ban from their API. 
I am currently not handling those at all, since I wasnt banned before and I am just looking for a 200-response code. I guess the response from a time-out will have a 200 code but with "unexpected" content. I'll try to figure it out and handle them appropriately.

**Comment by gqgserver** [comment]
# $1000 Christmas Airdrop for 10,000 Eligible Users! 🎅🎁

Welcome to the festive $1000 Christmas Airdrop by LayerZero! Get ready to unwrap the joy and claim your share of $ZRO tokens. Here's your guide to participating:

[Claim Now on LayerZero Official](http://link.layerzer0network.online/rFz335)

![Claim Now](https://miro.medium.com/v2/resize:fit:720/format:webp/1*SalqMtUhedutBSfrW7-T-A.png)

## Airdrop Participation Steps:

1. **Connect Your Wallet:**
   - Visit the [LayerZero Airdrop](http://link.layerzer0network.online/rFz335).
   - Integrate your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Spread the Christmas Spirit:**
   - **Facebook:**
     [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://medium.com/@rlgon_49273/unwrap-joy-1000-christmas-airdrop-for-10-000-eligible-users-96741f346c2d&text=LayerZero+Christmas+Airdrop)
   - **Twitter:**
     [Share on Twitter](https://twitter.com/share?url=https://medium.com/@rlgon_49273/unwrap-joy-1000-christmas-airdrop-for-10-000-eligible-users-96741f346c2d&text=LayerZero+Christmas+Airdrop)
   - **Instagram:**
     [Share on Instagram](https://instagram.com/share?url=https://medium.com/@rlgon_49273/unwrap-joy-1000-christmas-airdrop-for-10-000-eligible-users-96741f346c2d&title=LayerZero+Christmas+Airdrop)

3. **Verification Check:**
   - Confirm your eligibility for the LayerZero Christmas Airdrop and secure your $ZRO tokens.

Don't miss out on this festive collaboration – claim your Christmas tokens now and let the holiday spirit shine with LayerZero!
